return {
  -- "nvim-telescope/telescope.nvim",
  -- keys = {
  --   -- disable the keymap to grep files
  --   -- {"<leader>/", false},
  --   -- -- change a keymap
  --   -- { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
  --   -- -- add a keymap to browse plugin files
  --   -- {
  --   --   "<leader>fp",
  --   --   function() require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root }) end,
  --   --   desc = "Find Plugin File",
  --   -- },
  --
  --   { "<leader>sf", "<cmd>Telescope find_files<cr>", desc = "[S]earch [F]iles" },
  --   { "<leader>sg", "<cmd>Telescope live_grep<cr>", desc = "[S]earch by [G]rep" },
  --   { "<leader>sw", "<cmd>Telescope grep_string<cr>", desc = "[S]earch current [W]ord" },
  --
  --   -- vim.keymap.set('n', '<leader>gf', require('telescope.builtin').git_files, { desc = 'Search [G]it [F]iles' })
  --   --     vim.keymap.set('n', '<leader>sf', require('telescope.builtin').find_files, { desc = '[S]earch [F]iles' })
  --   --     vim.keymap.set('n', '<leader>sh', require('telescope.builtin').help_tags, { desc = '[S]earch [H]elp' })
  --   --     vim.keymap.set('n', '<leader>sw', require('telescope.builtin').grep_string, { desc = '[S]earch current [W]ord' })
  --   --     vim.keymap.set('n', '<leader>sg', require('telescope.builtin').live_grep, { desc = '[S]earch by [G]rep' })
  --   --     vim.keymap.set('n', '<leader>sd', require('telescope.builtin').diagnostics, { desc = '[S]earch [D]iagnostics' })
  -- },
}
