# zsh performance tracing
# zmodload zsh/datetime
# setopt PROMPT_SUBST
# PS4='+$EPOCHREALTIME %N:%i> '
#
# logfile=$(mktemp zsh_profile.XXXXXXXX)
# echo "Logging to $logfile"
# exec 3>&2 2>$logfile
#
# setopt XTRACE

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

bindkey -e
bindkey "[D" backward-word
bindkey "[C" forward-word
setopt ignore_eof

export EDITOR='nvim'

if [ -f '/Users/ianmacaulay/workspaces/dotfiles/aliases' ]; then . '/Users/ianmacaulay/workspaces/dotfiles/aliases'; fi
if [ -f '/Users/ianmacaulay/workspaces/completion/alacritty.bash' ]; then . '/Users/ianmacaulay/workspaces/completion/alacritty.bash'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# PROMPT='%F{yellow}%~ %(?.%F{green}→.%F{red}→)%f '

zstyle ':completion:*' menu select
autoload -U compinit && compinit
zmodload -i zsh/complist

eval "$(starship init zsh)"

# zsh performance tracing
# unsetopt XTRACE
# exec 2>&3 3>&-
